image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_COMPOSE_VERSION: 1.25.5
  APP_NAME: secretnotes-api
  ENV_NAME: dev
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
  EB_APP_NAME: $APP_NAME-$ENV_NAME
  EB_ENV_NAME: $APP_NAME-$ENV_NAME-env

before_script:
  - docker info
  - apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install --upgrade pip
  - pip install awscli
  - pip install docker-compose==$DOCKER_COMPOSE_VERSION
  - echo "Logging in to Docker Hub..."
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker build -t $DOCKERHUB_USERNAME/$APP_NAME .

unit-test:
  stage: test
  script:
    - echo "Running unit tests..."
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test

e2e-test:
  stage: test
  script:
    - echo "Running e2e tests..."
    - docker-compose up -d
    - docker-compose -f docker-compose.e2e-test.yml up --abort-on-container-exit --exit-code-from e2e-test
    - docker-compose down

deploy:
  stage: deploy
  script:
    - echo "Deploying to Elastic Beanstalk..."
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 cp Dockerrun.aws.json s3://$EB_APP_NAME/Dockerrun.aws.json
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_COMMIT_SHA --source-bundle S3Bucket=$EB_APP_NAME,S3Key=Dockerrun.aws.json
    - aws elasticbeanstalk update-environment --environment-name $EB_ENV_NAME --version-label $CI_COMMIT_SHA
  # environment:
  #   name: $ENV_NAME
  #   url: http://$EB_ENV_NAME.$AWS_DEFAULT_REGION.elasticbeanstalk.com
  only:
    - master
