version: '3.9'
services:
  api:
    container_name: secretnotes-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app # any change to base folder should be reflected
      - /app/node_modules
    command: yarn start:dev # overrides CMD from dockerfile

  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
