version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run test
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
