apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretnotes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretnotes-api
  template:
    metadata:
      labels:
        app: secretnotes-api
    spec:
      containers:
        - name: secretnotes-api
          image: mcjovial/spherity
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 3000
          resources: # Add resource limits for the backend container
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
